const ACCESS_TOKEN_DURATION = 3000; // 5 minutes
const REFRESH_TOKEN_DURATION = 36000; // 60 minutes
const MAX_PROBLEM_FILE_SIZE = 10485760; // 1024 * 1024 * 10 = 10 MB
const DEFAULT_LIMIT = 10;
const DEFAULT_PAGE = 1;

module.exports = {
  ACCESS_TOKEN_DURATION,
  REFRESH_TOKEN_DURATION,
  MAX_PROBLEM_FILE_SIZE,
  DEFAULT_LIMIT,
  DEFAULT_PAGE,
};
